
# There is some level of abstraction between the RF dongle's HID and these commands,
# but these report IDs are still used in the responses.
# 0x0
RF_REPORT_HID_CMD = 0x01
# 0x02
RF_REPORT_RECENTLY_CMD_DEBUG_CMD = 0x03
RF_REPORT_ACTR_STATUS = 0x4
# 0x5 .. 0xF
RF_REPORT_FLAG_OP_A = 0x10 # FW_INFO?
RF_REPORT_FLAG_OP_B = 0x11 # GG_FLAG?
RF_REPORT_NEW_CR_FLAGS = 0x12
RF_REPORT_RATE = 0x13
RF_REPORT_BATTERY_LEVEL = 0x14
RF_REPORT_MCU_VERSION = 0x15
RF_REPORT_RF_IDS = 0x16
RF_REPORT_CHANGE_BEHAVIOR = 0x17 # handleReportRequestRFChangeBehavior
RF_REPORT_RF_VERSION = 0x18
RF_REPORT_RF_DETAIL_STATUS = 0x19
RF_REPORT_RF_STATUS = 0x1A
RF_REPORT_FINISH_COMMAND_MODE = 0x1B # rf_spi_gotResult
# 0x1C
RF_REPORT_1D = 0x1D # returns the same data as 0x1E. Response to pairing cmds?
RF_REPORT_1E = 0x1E # returns the same data as 0x1D
RF_REPORT_RF_REBOOT = 0x1F
# 0x20 .. 0x2F
RF_REPORT_FOTA_INIT = 0x30
RF_REPORT_FOTA_MODE_SWITCH = 0x31
RF_REPORT_FOTA_DEINIT = 0x32
RF_REPORT_FOTA_WRITE_FW = 0x33
RF_REPORT_FOTA_MARK_TARGET = 0x34
# 0x35 .. 0x3F
RF_REPORT_FWU_INIT = 0x40
RF_REPORT_FWU_ERASE = 0x43
RF_REPORT_FWU_WRITE = 0x44
RF_REPORT_FWU_COMPUTE_CRC = 0x45
RF_REPORT_FWU_GET_CRC = 0x46
RF_REPORT_FWU_SIGN = 0x48
# 0x49 .. 0x4F
RF_REPORT_RF_MODE_OP = 0x50 # not 100% on this?
RF_REPORT_WRITE_RF = 0x51
# 0x52 .. 0x5F
RF_REPORT_WATCHDOG_TEST = 0x68
RF_REPORT_BATTERY_OP = 0x6A
RF_REPORT_USB_REPAIR = 0x6E
RF_REPORT_CALIB_OP = 0x6F