# Work state enum, set by HORUS_CMD_POWER
WS_STANDBY = 0x0
WS_CONNECTING = 0x1
WS_REPAIRING = 0x2
WS_CONNECTED = 0x3
WS_TRACKING = 0x4
WS_RECOVERY = 0x5
WS_REBOOT = 0x6
WS_SHUTDOWN = 0x7
WS_OCVR = 0x8
WS_PCVR = 0x9
WS_EYVR = 0xa
WS_RESTART = 0xb

# Error returns
ERR_BUSY = 0x2
ERR_03 = 0x3
ERR_UNSUPPORTED = 0xEE


PAIRSTATE_1 = 0x0001
PAIRSTATE_2 = 0x0002
PAIRSTATE_4 = 0x0004
PAIR_STATE_PAIRED = 0x0008
PAIRSTATE_10 = 0x0010

# SetStatus/GetStatus
HDCC_BATTERY = 0x0
HDCC_IS_CHARGING = 0x1
HDCC_POGO_PINS = 0x3
HDCC_DEVICE_ID = 0x4
HDCC_TRACKING_HOST = 0x5
HDCC_WIFI_HOST = 0x6
HDCC_7 = 0x7 # LED?
HDCC_FT_OVER_WIFI = 0x8
HDCC_ROLE_ID = 0xA
HDCC_WIFI_CONNECTED = 0xC
HDCC_HID_CONNECTED = 0xD
HDCC_E = 0xE # related to ROLE_ID? Sent on pairing.
HDCC_WIFI_ONLY_MODE = 0xF
HDCC_10 = 0x10 # pose related

TRACKING_MODE_NONE = -1 # checks persist.lambda.3rdhost
TRACKING_MODE_1 = 1 # gyro only? persist.lambda.3rdhost=0, persist.lambda.normalmode=1 persist.lambda.trans_setup=0
TRACKING_MODE_2 = 2 # body?
TRACKING_MODE_SLAM_CLIENT = 11 # gyro only? persist.lambda.3rdhost=0, persist.lambda.normalmode=0 # client?
TRACKING_MODE_21 = 21 # body tracking? persist.lambda.3rdhost
TRACKING_MODE_SLAM_HOST = 20 # SLAM persist.lambda.3rdhost=1, persist.lambda.normalmode=0
# 22 also triggers wifi hosting but doesn't set as host?
TRACKING_MODE_51 = 51 # SetUVCStatus?

# GET_STATUS
KEY_TRANSMISSION_READY = 0
KEY_RECEIVED_FIRST_FILE = 1
KEY_RECEIVED_HOST_ED = 2
KEY_RECEIVED_HOST_MAP = 3
KEY_CURRENT_MAP_ID = 4
KEY_MAP_STATE = 5
KEY_CURRENT_TRACKING_STATE = 6

_slam_key_strs = ["TRANSMISSION_READY", "RECEIVED_FIRST_FILE", "RECEIVED_HOST_ED", "RECEIVED_HOST_MAP", "CURRENT_MAP_ID", "MAP_STATE", "CURRENT_TRACKING_STATE"]
def slam_key_to_str(idx):
    return _slam_key_strs[idx]

# Commands
ASK_ED = 0
ASK_MAP = 1
KF_SYNC = 2
RESET_MAP = 3

_map_status_strs = ["MAP_NOT_CHECKED","MAP_EXIST","MAP_NOTEXIST","MAP_REBUILT","MAP_SAVE_OK","MAP_SAVE_FAIL","MAP_REUSE_OK","MAP_REUSE_FAIL_FEATURE_DIFF","MAP_REUSE_FAIL_FEATURE_LESS","MAP_REBUILD_WAIT_FOR_STATIC","MAP_REBUILD_CREATE_MAP"]
def map_status_to_str(idx):
    return _map_status_strs[idx]

# Map status
MAP_NOT_CHECKED = 0
MAP_EXIST = 1
MAP_NOTEXIST = 2
MAP_REBUILT = 3
MAP_SAVE_OK = 4
MAP_SAVE_FAIL = 5
MAP_REUSE_OK = 6
MAP_REUSE_FAIL_FEATURE_DIFF = 7
MAP_REUSE_FAIL_FEATURE_LESS = 8
MAP_REBUILD_WAIT_FOR_STATIC = 9
MAP_REBUILD_CREATE_MAP = 10

# Pose state
_pose_status_strs = ["NO_IMAGES_YET", "NOT_INITIALIZED", "OK", "LOST", "RECENTLY_LOST", "SYSTEM_NOT_READY"]
def pose_status_to_str(idx):
    return _pose_status_strs[idx]

POSE_SYSTEM_NOT_READY = -1
POSE_NO_IMAGES_YET = 0
POSE_NOT_INITIALIZED = 1
POSE_OK = 2
POSE_LOST = 3
POSE_RECENTLY_LOST = 4

# imu state
POSESTATE_OK = 0
POSESTATE_LOST = 1
POSESTATE_UNINITIALIZED = 2
POSESTATE_RECOVER = 3
POSESTATE_FOV_BOUNDARY = 4
POSESTATE_FOV_OCCLUSION = 5
POSESTATE_DEAD_ZONE = 6
POSESTATE_NOMEASUREMENT = 7
POSESTATE_NONCONVERGE = 8
POSESTATE_IK = 9
POSESTATE_INTEGRATOR = 10
POSESTATE_NEW_MAP = 11

SYSTEM_STATE_NONE = 0
SYSTEM_STATE_INIT = 1
SYSTEM_STATE_SAVE_ROOM_SETUP = 2
SYSTEM_STATE_ACTIVE = 3