
# Internal LED thread
LED_CMD_INIT = 0x0
LED_CMD_SET_LED = 0x1

# Internal Horus CMD thread
HORUS_CMD_POWER = 0x0
HORUS_CMD_UVC = 0x1
HORUS_CMD_LED_STATUS_UPDATE = 0x2
HORUS_CMD_VRC_APPEAR = 0x3
HORUS_CMD_VRC_DISAPPEAR = 0x4
HORUS_CMD_VRC_POWEROFF = 0x5
HORUS_CMD_CAMERA_SSR = 0x6
HORUS_CMD_IMU_SSR = 0x7
HORUS_CMD_DO_FT = 0x8
HORUS_CMD_FT_APPEAR = 0x9
HORUS_CMD_FT_DISAPPEAR = 0xA
HORUS_CMD_UPDATE_DEVICE_ID = 0xB
HORUS_CMD_SET_TRACKING_MODE = 0xC

HORUS_POWER_STANDBY = 0
HORUS_POWER_OCVR = 8
HORUS_POWER_PCVR = 9
HORUS_POWER_WIFI = 10

# Internal Horus BT thread
BT_CMD_INIT = 0x0
BT_CMD_ONOFF = 0x1
BT_CMD_REPAIR = 0x2
BT_CMD_RESTART = 0x3
BT_CMD_SEND_ACK = 0x4
BT_CMD_SEND_DATA = 0x5
BT_CMD_QUIT = 0x6

# maybe?
BT_CMD_CONNECTED = 0x33
BT_CMD_DISCONNECTED = 0x34
BT_CMD_ACK = 0xC9
BT_CMD_CA = 0xCA
BT_CMD_E7 = 0xE7

# Internal Horus RF thread?
RF_CMD_SET_CTL_HAPTIC = 0x0
RF_CMD_SET_CTL_POWERON = 0x1
RF_CMD_SET_CTL_POWEROFF = 0x2
RF_CMD_SET_CTL_REBOOT = 0x3
RF_CMD_SET_CTL_CAR_LED = 0x4
RF_CMD_SET_CTL_POWEROFF_CLEAR_PAIR_LIST = 0x5
RF_CMD_SET_FINGER_OUTPUT = 0x6
RF_CMD_SET_SILENT_CALIBRATION = 0x7
RF_CMD_SET_LPF = 0x8
RF_CMD_SET_HAND = 0x9
# ?
RF_CMD_SET_ROLE_ID = 0xB
RF_CMD_SET_FUSION_MODE = 0xC
RF_CMD_SET_EVENT_ON = 0xD
RF_CMD_SET_WAIT_START_IMU = 0xE
RF_CMD_QUIT = 0xF

FT_PORT = 8053